sudo: required
dist: trusty

language: haxe

haxe:
 - "3.4.7"
 - "development"

matrix:
 allow_failures:
   - haxe: development

install:
 - haxelib install lime
 - haxelib install openfl
 - haxelib install flixel
 - haxelib install flixel-addons
 - haxelib dev zerolib .

script:
 - lime build neko

deploy:
 - provider: script
   haxe: 3.4.7
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
     tags: true